Projekat/Proj/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Projekat.Models
{
    public class Film
    {

        public int FilmID { get; set; }
        [Display(Name = "Naziv")]
        public string naziv { get; set; }
        [Display(Name = "Trajanje(min)")]
        public int trajanje { get; set; }
        [Display(Name = "Ocjena")]
        public double ocjena { get; set; }
        [Display(Name = "Godina filma")]
        public int godinaFilma { get; set; }
        [Display(Name = "Broj ocjena")]
        public int brojOcjena { get; set; }
        [Display(Name = "Opis filma")]
        public string opisFilma { get; set; }
        [Display(Name = "Režija")]
        public string reziser { get; set; }
        [Display(Name = "Cijena")]
        public double cijena { get; set; }
        public string poster { get; set; }
        public string link { get; set; }


    }
}

Projekat/Proj/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projekat.Models;

namespace Projekat.Controllers
{
    public class FilmController : Controller
    {
        private readonly CDContext _context;

        public FilmController(CDContext context)
        {
            _context = context;
        }

        // GET: Film
        public async Task<IActionResult> Index(string upit)
        {
            var filmovi = _context.Film.AsQueryable();

            if (!string.IsNullOrEmpty(upit))
            {
                filmovi = filmovi.Where(x => x.naziv.Contains(upit));
            }


            return View(await filmovi.ToListAsync());
        }



        public async Task<IActionResult> Browse(string upit)
        {
            var filmovi = _context.Film.AsQueryable();

            if (!string.IsNullOrEmpty(upit))
            {
                filmovi = filmovi.Where(x => x.naziv.Contains(upit));
            }


            return View(await filmovi.ToListAsync());
        }






        // GET: Film/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film
                .FirstOrDefaultAsync(m => m.FilmID == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // GET: Film/Create
        public IActionResult Create()
        {
            return View();
        }

     
        public async Task<IActionResult> Base(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            ViewBag.podatak = film.poster;


          //  VarGlobal.PickedMovieID = id;
            return View(film);
        }

        // POST: Film/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FilmID,naziv,trajanje,ocjena,godinaFilma,brojOcjena,opisFilma,reziser,cijena,poster,link")] Film film)
        {
            if (ModelState.IsValid)
            {
                _context.Add(film);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Film/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            return View(film);
        }

        // POST: Film/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FilmID,naziv,trajanje,ocjena,godinaFilma,brojOcjena,opisFilma,reziser,cijena,poster,link")] Film film)
        {
            if (id != film.FilmID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.FilmID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Film/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film
                .FirstOrDefaultAsync(m => m.FilmID == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Film/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var film = await _context.Film.FindAsync(id);
            _context.Film.Remove(film);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(int id)
        {
            return _context.Film.Any(e => e.FilmID == id);
        }
    }
}

Projekat/Proj/Views/Film/Base.cshtml
@using Projekat.Models
@model Film


<br />
<div class="row">
    <div class="col-md-4">

        <section id="picture">
            <img src=@ViewBag.podatak alt="Sample Image" width="300" height="500" />

        </section>
    </div>
 
    <div class="col-md-6">

        <section id="informations">


            <div class="form-group">
                @Html.LabelFor(m => m.naziv, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.naziv, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(m => m.naziv, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />
            <br />
            <div class="form-group">
                @Html.LabelFor(m => m.godinaFilma, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.godinaFilma, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(m => m.godinaFilma, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />

            <div class="form-group">
                @Html.LabelFor(m => m.ocjena, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.ocjena, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(m => m.ocjena, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />

            <div class="form-group">
                @Html.LabelFor(m => m.trajanje, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.trajanje, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(m => m.trajanje, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />

            

            <div class="form-group">
                @Html.LabelFor(m => m.reziser, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.reziser, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(m => m.reziser, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />

           

            <div class="form-group">
                @Html.LabelFor(m => m.cijena, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.cijena, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(m => m.cijena, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <br />

        </section>

    </div>



    <section id="description">
        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(m => m.opisFilma, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.opisFilma, new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(m => m.opisFilma, "", new { @class = "text-danger" })
                </div>
            </div>


        </div>
    </section>


</div>

<br />
<br />
<div class="row">
    <div class="col-md-4">
        <section id="Ocjene">
            <div class="col-md-offset-3 col-md-10">
                <label title="text">Add a rate</label>
            </div>
            <div>
                <div class="col-md-offset-2 col-md-10">
                    <input type="radio" id="star5" name="rate" value="5" />
                    <label for="star5" title="text">5</label>
                    <input type="radio" id="star6" name="rate" value="6" />
                    <label for="star6" title="text">6</label>
                    <input type="radio" id="star7" name="rate" value="7" />
                    <label for="star7" title="text">7</label>
                    <input type="radio" id="star8" name="rate" value="8" />
                    <label for="star8" title="text">8</label>
                    <input type="radio" id="star9" name="rate" value="9" />
                    <label for="star9" title="text">9</label>
                    <input type="radio" id="star10" name="rate" value="10" />
                    <label for="star10" title="text">10</label>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-3 col-md-10">
                    <a href="https://yts.mx/torrent/download/A52324E4506C66CB30067BE13EE366C225BC4D70">Kupi film</a>
                </div>
            </div>
        </section>
    </div>
    <div class="col-md-4">

        <div class="form-group">
            <div class="col-md-offset-5 col-md-8">
                <input type="submit" value="Add on wishlist" class="btn btn-primary" />
            </div>
        </div>
        <br />
        <br />

        <div class="form-group">
            <div class="col-md-offset-5 col-md-12">
                <input type="submit" value="Add on watched list" class="btn btn-primary" />
            </div>
        </div>
    </div>
</div>

Projekat/Proj/Views/Film/Browse.cshtml
@model IEnumerable<Projekat.Models.Film>
@{
    ViewData["Title"] = "Browse";




    var eachFilm = ViewData["listaFilmova"] as Projekat.Models.Film;

}




<form asp-controller="Film" asp-action="Index">
    <p>

        Pretraga: <input type="text" name="upit" />
        <input type="submit" value="Pretrazi" />
    </p>


</form>









<section>
    <div class="row">




        @foreach (var item in Model)
        {
            <div class="browse-movie-wrap col-xs-10 col-sm-4 col-md-5 col-lg-4">
               
                    <a asp-action="Base" asp-route-id="@item.FilmID">

                    <figure>
                        <img class="img-responsive" src=@item.poster alt="Spiritual Kung Fu (1978) download" width="170" height="255">
                    </figure>
                </a>
                <div class="browse-movie-bottom">
                   <a asp-action="Base" asp-route-id="@item.FilmID" class="browse-movie-title">@item.naziv</a>
                    <div class="browse-movie-year">@item.godinaFilma</div>
                </div>
            </div>
        }





    </div>
</section>

Projekat/Proj/Views/Film/Create.cshtml
@model Projekat.Models.Film

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Film</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="naziv" class="control-label"></label>
                <input asp-for="naziv" class="form-control" />
                <span asp-validation-for="naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="trajanje" class="control-label"></label>
                <input asp-for="trajanje" class="form-control" />
                <span asp-validation-for="trajanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ocjena" class="control-label"></label>
                <input asp-for="ocjena" class="form-control" />
                <span asp-validation-for="ocjena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="godinaFilma" class="control-label"></label>
                <input asp-for="godinaFilma" class="form-control" />
                <span asp-validation-for="godinaFilma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="opisFilma" class="control-label"></label>
                <input asp-for="opisFilma" class="form-control" />
                <span asp-validation-for="opisFilma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="reziser" class="control-label"></label>
                <input asp-for="reziser" class="form-control" />
                <span asp-validation-for="reziser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cijena" class="control-label"></label>
                <input asp-for="cijena" class="form-control" />
                <span asp-validation-for="cijena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="poster" class="control-label"></label>
                <input asp-for="poster" class="form-control" />
                <span asp-validation-for="poster" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="link" class="control-label"></label>
                <input asp-for="link" class="form-control" />
                <span asp-validation-for="link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projekat/Proj/Views/Film/Delete.cshtml
@model Projekat.Models.Film

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.trajanje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.trajanje)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ocjena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ocjena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.godinaFilma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.godinaFilma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.brojOcjena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.brojOcjena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.opisFilma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.opisFilma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.reziser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.reziser)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cijena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cijena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.poster)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.poster)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.link)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FilmID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Projekat/Proj/Views/Film/Details.cshtml
@model Projekat.Models.Film

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.trajanje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.trajanje)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ocjena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ocjena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.godinaFilma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.godinaFilma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.brojOcjena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.brojOcjena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.opisFilma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.opisFilma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.reziser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.reziser)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cijena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cijena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.poster)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.poster)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.link)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.FilmID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Projekat/Proj/Views/Film/Edit.cshtml
@model Projekat.Models.Film

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Film</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FilmID" />
            <div class="form-group">
                <label asp-for="naziv" class="control-label"></label>
                <input asp-for="naziv" class="form-control" />
                <span asp-validation-for="naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="trajanje" class="control-label"></label>
                <input asp-for="trajanje" class="form-control" />
                <span asp-validation-for="trajanje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ocjena" class="control-label"></label>
                <input asp-for="ocjena" class="form-control" />
                <span asp-validation-for="ocjena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="godinaFilma" class="control-label"></label>
                <input asp-for="godinaFilma" class="form-control" />
                <span asp-validation-for="godinaFilma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="brojOcjena" class="control-label"></label>
                <input asp-for="brojOcjena" class="form-control" />
                <span asp-validation-for="brojOcjena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="opisFilma" class="control-label"></label>
                <input asp-for="opisFilma" class="form-control" />
                <span asp-validation-for="opisFilma" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="reziser" class="control-label"></label>
                <input asp-for="reziser" class="form-control" />
                <span asp-validation-for="reziser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cijena" class="control-label"></label>
                <input asp-for="cijena" class="form-control" />
                <span asp-validation-for="cijena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="poster" class="control-label"></label>
                <input asp-for="poster" class="form-control" />
                <span asp-validation-for="poster" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="link" class="control-label"></label>
                <input asp-for="link" class="form-control" />
                <span asp-validation-for="link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projekat/Proj/Views/Film/Index.cshtml
@model IEnumerable<Projekat.Models.Film>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista filmova</h1>





<form asp-controller="Film" asp-action="Index">
    <p>

        Pretraga: <input type="text" name="upit" />
        <input type="submit" value="Pretrazi" />
    </p>


</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.naziv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.trajanje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ocjena)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.godinaFilma)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.brojOcjena)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.reziser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cijena)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.trajanje)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ocjena)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.godinaFilma)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.brojOcjena)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.reziser)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cijena)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.FilmID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.FilmID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.FilmID">Delete</a> |
                    <a asp-action="Base" asp-route-id="@item.FilmID">Base</a>
                </td>
            </tr>
        }
    </tbody>
</table>